export const CHANGE_PROJECT_NAME = 'CHANGE_PROJECT_NAME';
export const CHANGE_OWNER_NAME = 'CHANGE_OWNER_NAME';
export const SWAP_CHART_ACTIVE = 'SWAP_CHART_ACTIVE';
export const HOVER_CHART = 'HOVER_CHART';
export const UNHOVER_CHART = 'UNHOVER_CHART';
